version: '3.4'

services:
  fleetmanagement:
    image: ${DOCKER_REGISTRY-}fleetmanagement
    build:
      context: .
      dockerfile: FleetManagement/Dockerfile
    links:
      - mssql

  mssql:
     image: mcr.microsoft.com/mssql/server:2019-latest

  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4